line_length: 136

disabled_rules:
  - todo
  - force_try
  - force_cast
  - trailing_comma
  - large_tuple

excluded:
  - StudKit/Vendors
  - StudKitTests/Vendors
  - Carthage

identifier_name:
  excluded:
    - id
    - to

type_name:
  excluded:
    - UI

force_try:
  excluded:
    - StudAppTests
    - StudAppUITests
    - StudKitTests
