line_length: 128

disabled_rules:
  - todo
  - force_try
  - force_cast
  - trailing_comma
  - large_tuple

excluded:
  - StudKit/Vendors
  - StudKitTests/Vendors

identifier_name:
  excluded:
    - id

type_name:
  excluded:
    - UI

force_try:
  excluded:
    - StudAppTests
    - StudAppUITests
    - StudKitTests
